### ISSUE TITLE
rhel7 symphony server web services testing

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/myaccount#279]

**Comment by cdmo** [comment]
What does a "down for system maintenance" response from My Account look like

**Comment by ruthtillman** [comment]
@cdmo what's language we use for availabiltiy on the catalog?

**Comment by banukutlu** [comment]
We had sth like the below for availability:

```Required system maintenance is currently being performed. Availability and I Want It functions should be restored by midnight November 3rd. <a href="https://libraries.psu.edu/alerts">See library alerts</a> for updates and details.```

**Comment by ruthtillman** [comment]
Hm, then maybe something like:

`Required system maintenance is currently being performed. Availability and I Want It functions should be restored by [date/time]. <a href="https://libraries.psu.edu/alerts">See library alerts</a> for updates and details.` for the catalog part and

something like:
`Due to required system maintenance, My Library Account will be in read-only mode until [date/time]. Renewals and Holds management will be unavailable. <a href="https://libraries.psu.edu/alerts">See library alerts</a> for updates and details.`

**Comment by cdmo** [comment]
My question above wasn't so much about language but rather, what does "down" look like in terms of how the application works. The answer we got yesterday during our touch base with the Symphony team answered that: read only but not "down for maintenance." I'm going close this issue as we have done "rhel7 symphony server web services testing" - please reopen if you feel like we need more testing of the web service? I'm working on read only over at #291

**Comment by cdmo** [comment]
I noticed you used "My Library Account" in the message. Are we changing the application name now? Otherwise it seems kinda strange seeing as how it's branded heavily with "MyAccount." The subdomain is even `myaccount`. Are we going to rename?

**Comment by ruthtillman** [comment]
I don't think so, just trying to make sure people understand it during the transition.
