### ISSUE TITLE
Adding page for users to opt-into wage garnishment

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#484]
If user is status: Barred AND they don't have anything in the garnish date (some users will have 0), we want them to be able to opt in and update the system.

## WDDLL

- [ ] We have a page where people can check a box to opt in and that box will update the page.
- [ ] Additional feature: when a barred user logs into My Account or attempts to place a hold, we test their account to see if they should opt-in and then offer this page?
  - [ ] And should we then check if they're barred AND 00000 but they _might_ be from Law or Medicine, @mkutch is the field still just 000000?

## Web Services Calls

@mkutch - what are Web Service calls for:

1. Changing user status from Barred to... ok?
2. Updating the date in the field garnish date (should the date format be YYYYMMDD?) 

## Page Text / Fields

Updated version from Chris H.:

```
## Accept Library Fee Policy for University Employees

I authorize the Libraries, after appropriate notice, to deduct from my paycheck any fees incurred. Additional fees may be charged for this process. Library borrowing privileges are contingent upon this authorization. 

For more information about library fees and payment, please visit: https://libraries.psu.edu/policies/ul-ad20

[checkbox and button to confirm acceptance]

```
## Thank You. 

Thank you for accepting the Libraries' Fee Policy.

```

## Questions

What's the error users get when they place a hold and are barred? Can we set that up too?

**Comment by banukutlu** [comment]
@mkutch Can you get us a screenshot from the current cat page?

**Comment by mkutch** [comment]
Here is the start page of the accept lending code. You can go through it to see the different pages. It will just update your garnish date to current date.
https://cat.libraries.psu.edu/accept_lendingcode.html

@tdouty will look into the C code and let us know what the code does, as to not miss any cases. I'll post web service calls.

**Comment by mkutch** [comment]
This is the web service call to get the extended info 

https://cat-stage.libraries.psu.edu:28443/symwsbc/user/patron/key/18511?includeFields=library,standing,customInformation{patronExtendedInformation{*}}

userstatus is in the standing field.

This lists all customInformation{patronExtendedInformation} whether or not there is data. It puts out an output for every extended info entry even if null.  I have a Sirsi ticket in regarding why null data is being output since they said the output should look like dumpflatuser which only outputs extended info with data. 

According to their SDK docs, when you want to update the user extended info

> User extended information.
> 
> Used by the customInformation list in the patron resource, this stores data regarding an extended information entry.
> 
> When modifying the extended information for a patron, it is important to include all entries that should be kept in the request. Entries that were not already present will be added, and entries that were present but were removed from the list will be deleted. This also includes entries that change position.
> 


So you need to include all the extended info data that's not null along with the fields you want to update.
The web service call to update patron 
https://cat-stage.libraries.psu.edu:28443/symwsbc/user/patron/key/ with PUT method.

@banukutlu  let me know if you have questions or need more info.

**Comment by ruthtillman** [comment]
url slug: https://myaccount.libraries.psu.edu/accept-lending-policy

**Comment by nicktiberi** [comment]
@mkutch — I am trying to test this against Symphony QA. Should I be able to update my user's patron standing from its current state of "OK" to "BARRED"? Or is barred represented by a different key?

**Comment by mkutch** [comment]
Yes you can change your standing for testing purposes from "OK" to "BARRED"  and vice versa.  Let me know if it doesn't work.

**Comment by mkutch** [comment]
@nicktiberi  you'll need to add this to the header

  `SD-Prompt-Return:USER_EDIT_OVRCD/<OVERRIDE_PWD>
`

I tried it and it worked. Let  me know if it works for you too or you need other help
