### ISSUE TITLE
Sending Hershey folks to Hershey ILLiad

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/myaccount#622]
We've worked out with Hershey that their statuses and policies for this process will be exactly the same as the ones we're currently using for the rest-of-PSU-ILLiad. 

Hershey's ILLiad will be the same params, etc., except they will be `mhy` instead of `upm`.

We would have to determine the most efficient way to direct users there. They should all have the home library of HERSHEY in Symphony. So one way might be to split them out at the point at which we're splitting off the folks who don't get ILL at all and then set a parameter of whether it should be UPM or MHY.

**Comment by ajkiessl** [comment]
@ruthtillman @banukutlu I think I've got the first part of this issue down, but I want to clarify some things before going further.  I'm assuming we first want to identify if a user is from Hershey.  It looks like we can do that by checking their "library" attribute in the patron info returned from Symphony.  I can't totally confirm this, though, since I'm not affiliated with Hershey. 

I'm not too sure what the expected behavior from here is?  I've noticed that the "Manage your Interlibrary Loans" link url contains `upm` in it's path.  Do we just want this to dynamically change to `mhy` when we have a Hershey user?  Will all of the API calls have to change in some way too?  I'm not seeing `upm` anywhere in the API URLs/paths.

**Comment by whereismyjetpack** [comment]
After digging into this quite a bit, it seems that hershey doesn't have their own illiad as much as they have their own view into illiad. I think we might need to change the `NVTGC` parameter when creating a hershey user, however. it's presently hardcoded to `UPILL`

If we could get a hershey user to query and validate that would be helpful. 

https://github.com/psu-libraries/myaccount/blob/5bc42a3065f6e63de6436566556d661057773b5b/app/services/illiad_client.rb#L51-L52

**Comment by ajkiessl** [comment]
Ah okay, thanks.  I guess there's the chance that the holds/checkouts API calls will all be the same?

I agree, it would be helpful to have a hershey user test this out.

**Comment by ruthtillman** [comment]
@ajkiessl @whereismyjetpack I can provide access IDs for someone with and someone without ILLiads at Hershey.
